name: Danger

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  job-danger:
    name: Review, Lint, Verify
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: Danger
        uses: danger/swift@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}